# Generated by Django 4.0 on 2022-04-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_alter_usercar_first_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='usercar',
            name='deleted_at',
        ),
    ]
